[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "Unicode-3.0",
]
private = { ignore = true }

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
